#!/usr/bin/env python3
"""Render the Codex custom-agent registry from the framework's role contract."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path


AGENTS = (
    ("adr-architect", "gpt-5.6-sol", "medium"),
    ("closure-auditor", "gpt-5.6-sol", "high"),
    ("code-reviewer", "gpt-5.6-terra", "medium"),
    ("concern-selector", "gpt-5.6-terra", "low"),
    ("discovery-agent", "gpt-5.6-terra", "low"),
    ("operational-architect", "gpt-5.6-sol", "medium"),
    ("performance-reviewer", "gpt-5.6-terra", "medium"),
    ("production-readiness", "gpt-5.6-sol", "medium"),
    ("security-reviewer", "gpt-5.6-sol", "high"),
    ("staff-engineer", "gpt-5.6-sol", "high"),
    ("test-architect", "gpt-5.6-sol", "medium"),
    ("threat-modeler", "gpt-5.6-sol", "high"),
)


def render(name: str, model: str, effort: str) -> str:
    source = f".claude/agents/{name}.md"
    return f'''# Generated by tooling/codex/generate_agents.py. Do not hand-edit.
name = "{name}"
description = "Codex delivery adapter for the {name} governance role."
model = "{model}"
model_reasoning_effort = "{effort}"
sandbox_mode = "read-only"

developer_instructions = """
You are the `{name}` role in AI Grounded's Codex delivery layer.

Before doing any analysis, read `{source}`. Its role definition, scope boundaries,
required inputs, output format, priority rubric, and coordination rules are
authoritative. Follow them exactly, except that this Codex adapter owns the
model and sandbox settings declared above.

Remain read-only: do not edit files, append events, invoke other agents, or run
state-changing commands. Return the complete artifact and ready-to-append event
content for the parent session to persist. If a parent session explicitly
overrides this sandbox, state that isolation is advisory in your artifact.
"""
'''


def expected_files(root: Path) -> dict[Path, str]:
    return {root / ".codex" / "agents" / f"{name}.toml": render(name, model, effort)
            for name, model, effort in AGENTS}


def write(root: Path) -> None:
    for path, content in expected_files(root).items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")


def check(root: Path) -> list[Path]:
    return [path for path, content in expected_files(root).items()
            if not path.exists() or path.read_text(encoding="utf-8") != content]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo-root", default=".")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    root = Path(args.repo_root).resolve()
    if args.check:
        drifted = check(root)
        if drifted:
            for path in drifted:
                print(f"DRIFT: {path.relative_to(root)}")
            return 1
        print(f"codex-agent-config: {len(AGENTS)} agent configurations match")
        return 0
    write(root)
    print(f"codex-agent-config: rendered {len(AGENTS)} agent configurations")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
