#!/usr/bin/env python3
"""Render the project Codex permission profile from the reviewed registry."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from policy_registry import SENSITIVE_PATH_GLOBS


def render() -> str:
    rules = "\n".join(f'"{path}" = "deny"' for path in SENSITIVE_PATH_GLOBS)
    return f'''# Generated by tooling/codex/generate_config.py. Do not hand-edit.
# Requires Codex CLI 0.146.1 or later; validate with tooling/codex/capabilities.py.

default_permissions = "ai-grounded"

[windows]
# Read-only child roles need the stronger native Windows sandbox. Codex requests
# administrator approval to set it up on first use.
sandbox = "elevated"

[agents]
max_concurrent_threads_per_session = 4

[permissions.ai-grounded]
description = "Workspace editing with credential-bearing paths denied."
extends = ":workspace"

[permissions.ai-grounded.filesystem]
glob_scan_max_depth = 6

[permissions.ai-grounded.filesystem.":workspace_roots"]
{rules}
'''


def config_path(root: Path) -> Path:
    return root / ".codex" / "config.toml"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo-root", default=".")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    path = config_path(Path(args.repo_root).resolve())
    expected = render()
    if args.check:
        if not path.exists() or path.read_text(encoding="utf-8") != expected:
            print(f"DRIFT: {path}")
            return 1
        print("codex-config: generated permission profile matches")
        return 0
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(expected, encoding="utf-8")
    print(f"codex-config: rendered {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
