#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Myoung Hong
"""
describe.py - the self-describing gate inventory.

Guidance kept drifting behind the gate chain: workflow skills named tools that no
longer matched what pre-commit.d/ actually runs, and a hand-maintained gate list is
just another declaration that disagrees with the disk. The durable fix is to make
the inventory DERIVE from the source of truth (the gate files themselves) rather
than restate it, so there is only one copy of the fact and it cannot drift.

Each gate in .githooks/pre-commit.d/ carries a machine-readable gate-meta header:

    # gate-meta:
    #   order: 10
    #   name: gitleaks
    #   posture: fail-closed        (fail-closed | report-only)
    #   skip: SKIP_GITLEAKS
    #   strict: none                (the *_STRICT env var, or none)
    #   summary: one line, what it checks and why
    # end-gate-meta

This tool scans the executable gates (matching the dispatcher's own rule: every
executable file in pre-commit.d/), parses those headers, also inventories the
on-demand tooling/*/ tools (best-effort, from each tool's README/docstring), and
emits the inventory as Markdown (default) or JSON.

--check mode is the anti-drift enforcement: it regenerates the inventory, compares
it to the committed doc, and reports two kinds of problem: a gate missing or with a
malformed gate-meta header (a new gate cannot ship undescribed), and a committed
inventory that no longer matches the gates on disk (drift). Report-only by default
(exit 0); --strict exits 1 on any problem, so CI and the meta-gate can enforce.

The pure core (header parsing, validation, rendering, drift comparison) is
stdlib-only and unit-testable. Filesystem scanning is the thin shell.

Usage:
    python3 tooling/gates/describe.py                       # print Markdown inventory
    python3 tooling/gates/describe.py --json
    python3 tooling/gates/describe.py --check [--strict]    # validate headers + drift
    python3 tooling/gates/describe.py --write                # regenerate the committed UTF-8 doc
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from pathlib import Path

REQUIRED_KEYS = ["order", "name", "posture", "skip", "strict", "summary"]
POSTURES = {"fail-closed", "report-only"}
DOC_PATH = "docs/GATES.md"
GENERATED_MARK = "<!-- generated by tooling/gates/describe.py; do not edit by hand -->"


# ---------------- pure core ----------------


def parse_gate_header(text: str):
    """Pure. Extract the gate-meta block from a gate file's text. Returns a dict of
    fields (raw strings), or None if no block is present."""
    m = re.search(r"#\s*gate-meta:\s*\n(.*?)#\s*end-gate-meta", text, re.DOTALL)
    if not m:
        return None
    fields = {}
    for line in m.group(1).splitlines():
        s = line.lstrip()
        if not s.startswith("#"):
            continue
        s = s[1:].strip()
        if not s or ":" not in s:
            continue
        key, _, val = s.partition(":")
        fields[key.strip()] = val.strip()
    return fields


def validate_gate(meta) -> list:
    """Pure. Problems with a parsed gate-meta dict (missing keys, bad posture, bad
    order). An empty list means valid."""
    problems = []
    if meta is None:
        return ["no gate-meta header"]
    for k in REQUIRED_KEYS:
        if k not in meta or meta[k] == "":
            problems.append(f"missing gate-meta key: {k}")
    if "posture" in meta and meta["posture"] not in POSTURES:
        problems.append(f"posture must be one of {sorted(POSTURES)}, got '{meta['posture']}'")
    if "order" in meta and not re.match(r"^\d+$", meta.get("order", "")):
        problems.append(f"order must be an integer, got '{meta.get('order')}'")
    return problems


def render_markdown(gates, tools) -> str:
    """Pure. gates: list of dicts with file + meta (+ problems). tools: list of
    (name, summary). Deterministic output so --check's diff is stable."""
    lines = [GENERATED_MARK, "", "# Gate chain and tooling inventory", "",
             "Generated from the gate-meta headers in `.githooks/pre-commit.d/` and the",
             "`tooling/*/` tools. Do not edit by hand; run `tooling/gates/describe.py`.",
             "", "## Commit-time gate chain", "",
             "Run by `.githooks/pre-commit` after the loop-closure gate, in order.", "",
             "| order | gate | posture | skip | strict | purpose |",
             "|---|---|---|---|---|---|"]
    for g in sorted(gates, key=lambda x: int(x["meta"].get("order", "999")) if x["meta"] and re.match(r"^\d+$", x["meta"].get("order", "")) else 999):
        m = g["meta"] or {}
        lines.append(f"| {m.get('order','?')} | {m.get('name', g['file'])} | "
                     f"{m.get('posture','?')} | {m.get('skip','?')} | {m.get('strict','?')} | "
                     f"{m.get('summary','?')} |")
    lines += ["", "## On-demand tools (`tooling/`)", "",
              "Advisory tools run at checkpoints or in CI, not on every commit.", ""]
    for name, summary in sorted(tools):
        lines.append(f"- `tooling/{name}/`: {summary}")
    return "\n".join(lines) + "\n"


# ---------------- filesystem shell ----------------


def discover_gates(hook_dir: Path):
    """Every executable file in pre-commit.d/ (the dispatcher's own rule), with its
    parsed+validated gate-meta. README.md and other non-executables are skipped, as
    the dispatcher skips them."""
    out = []
    if not hook_dir.is_dir():
        return out
    for p in sorted(hook_dir.iterdir()):
        if not p.is_file() or p.suffix == ".md" or not os.access(p, os.X_OK):
            continue
        meta = parse_gate_header(p.read_text(encoding="utf-8", errors="replace"))
        out.append({"file": p.name, "meta": meta, "problems": validate_gate(meta)})
    return out


def _first_prose_line(text: str) -> str:
    for line in text.splitlines():
        s = line.strip().lstrip("#").strip()
        if s and not s.startswith("<!--") and not s.startswith("```"):
            return s
    return ""


def _cap(s: str, n: int = 100) -> str:
    s = s.strip()
    return s if len(s) <= n else s[: n - 1].rstrip() + "..."


def tool_summary(tool_dir: Path) -> str:
    readme = tool_dir / "README.md"
    if readme.exists():
        lines = readme.read_text(encoding="utf-8", errors="replace").splitlines()
        body = "\n".join(lines[1:]) if lines else ""
        s = _first_prose_line(body) or _first_prose_line("\n".join(lines))
        if s:
            return _cap(s)
    for py in sorted(tool_dir.glob("*.py")):
        if py.name.startswith("test_"):
            continue
        m = re.search(r'"""(.*?)"""', py.read_text(encoding="utf-8", errors="replace"), re.DOTALL)
        if m:
            doc = m.group(1).strip().splitlines()
            line = next((x.strip() for x in doc if x.strip()), "")
            line = re.sub(r"^\S+\.py\s*-\s*", "", line)
            if line:
                return _cap(line)
    return "(no summary)"


def discover_tools(tooling_dir: Path):
    out = []
    if not tooling_dir.is_dir():
        return out
    for d in sorted(tooling_dir.iterdir()):
        if not d.is_dir() or d.name in ("lib", "gates"):
            continue
        out.append((d.name, tool_summary(d)))
    return out


def generate(repo_root: Path) -> str:
    gates = discover_gates(repo_root / ".githooks" / "pre-commit.d")
    tools = discover_tools(repo_root / "tooling")
    return render_markdown(gates, tools)


def check(repo_root: Path) -> dict:
    """Validate headers and detect drift against the committed doc."""
    gates = discover_gates(repo_root / ".githooks" / "pre-commit.d")
    header_problems = [{"file": g["file"], "problems": g["problems"]} for g in gates if g["problems"]]
    generated = generate(repo_root)
    doc = repo_root / DOC_PATH
    committed = doc.read_text(encoding="utf-8") if doc.exists() else None
    drift = committed != generated
    return {
        "header_problems": header_problems,
        "doc_exists": committed is not None,
        "drift": drift,
        "ok": not header_problems and not drift,
    }


def main(argv=None) -> int:
    p = argparse.ArgumentParser(description="Self-describing gate inventory. --check is advisory unless --strict.")
    p.add_argument("--repo-root", default=".")
    p.add_argument("--json", action="store_true")
    p.add_argument("--check", action="store_true")
    p.add_argument("--strict", action="store_true")
    p.add_argument("--write", action="store_true",
                   help="Write the generated Markdown inventory as UTF-8 to docs/GATES.md.")
    args = p.parse_args(argv)
    repo_root = Path(args.repo_root)

    if args.check:
        rep = check(repo_root)
        if args.json:
            sys.stdout.write(json.dumps(rep, indent=2) + "\n")
        else:
            if rep["ok"]:
                sys.stdout.write("gates: inventory current; every gate has a valid gate-meta header.\n")
            else:
                for hp in rep["header_problems"]:
                    sys.stdout.write(f"gates: {hp['file']}: {'; '.join(hp['problems'])}\n")
                if not rep["doc_exists"]:
                    sys.stdout.write(f"gates: {DOC_PATH} is missing; run tooling/gates/describe.py > {DOC_PATH}\n")
                elif rep["drift"]:
                    sys.stdout.write(f"gates: {DOC_PATH} is stale (drift from the gates on disk); "
                                     f"regenerate: tooling/gates/describe.py > {DOC_PATH}\n")
        return 1 if (args.strict and not rep["ok"]) else 0

    out = generate(repo_root)
    if args.write:
        if args.json:
            p.error("--write cannot be combined with --json")
        (repo_root / DOC_PATH).write_text(out, encoding="utf-8")
        return 0
    if args.json:
        gates = discover_gates(repo_root / ".githooks" / "pre-commit.d")
        tools = discover_tools(repo_root / "tooling")
        sys.stdout.write(json.dumps({"gates": gates, "tools": tools}, indent=2) + "\n")
    else:
        sys.stdout.write(out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
