# /// script
# requires-python = ">=3.11"
# dependencies = ["pyyaml"]
# ///
"""
Substrate assembler.

Reads the authored granular form (catalogs/concerns/<concern>/<rule>/rule.yaml)
and generates the consumption artifacts under dist/:
  - dist/concerns/<concern>.oscal.yaml   one OSCAL catalog per concern
  - dist/index.yaml                       flat id -> path index for fast lookup

This is deterministic and idempotent. No AI is involved. Triggered by:
  - manual:     uv run governance-commons/tooling/assemble/assemble.py
  - pre-commit: run the validator (blocking) and optionally re-assemble
  - CI:         run validate then assemble; fail the build on any error

Layer maps to OSCAL prop 'layer' value:
  mechanical -> mechanical, semantic -> semantic, judgmental -> judgmental
"""
import sys
import pathlib
import yaml

ROOT = pathlib.Path(__file__).resolve().parents[2]          # governance-commons/
CONCERNS = ROOT / "catalogs" / "concerns"
DIST = ROOT / "dist"
NS = "governance-commons"


def load_yaml(p):
    with open(p) as fh:
        return yaml.safe_load(fh)


def prop(name, value):
    return {"name": name, "ns": NS, "value": value}


def rule_to_control(rule):
    """Map a clean authored rule into an OSCAL control."""
    rid = rule["id"]
    props = [
        prop("rule-id", rid),
        prop("layer", rule["layer"]),
        prop("characteristic", rule["characteristic"]),
        prop("severity", rule["severity"]),
        prop("lifecycle-status", rule["status"]),
    ]
    for c in rule.get("cwe", []):
        props.append(prop("cwe", c))
    at = rule.get("applies_to", {})
    for k in ("language", "framework", "environment"):
        if at.get(k):
            props.append(prop(f"applies-to-{k}", at[k]))
    for ref in rule.get("references", []):
        props.append(prop("references-rule", ref))

    links = []
    for s in rule.get("sources", []):
        link = {"rel": "authoritative-source", "text": s["title"]}
        if s.get("url"):
            link["href"] = s["url"]
        links.append(link)

    parts = [{"id": f"{rid}_smt", "name": "statement", "prose": rule["statement"].strip()}]
    if rule.get("rationale"):
        parts.append({"id": f"{rid}_rationale", "name": "rationale", "prose": rule["rationale"].strip()})

    control = {
        "id": rid,
        "class": "substrate-rule",
        "title": rule["name"],
        "props": props,
        "parts": parts,
    }
    if links:
        control["links"] = links
    return control


def assemble_concern(concern_dir):
    concern = load_yaml(concern_dir / "concern.yaml") or {}
    controls = []
    index_rows = []
    for rule_dir in sorted(p for p in concern_dir.iterdir() if p.is_dir()):
        ry = rule_dir / "rule.yaml"
        if not ry.exists():
            continue
        rule = load_yaml(ry) or {}
        controls.append(rule_to_control(rule))
        index_rows.append({
            "id": rule["id"],
            "concern": concern["id"],
            "layer": rule["layer"],
            "characteristic": rule["characteristic"],
            "status": rule["status"],
            "path": str(ry.relative_to(ROOT)),
        })

    catalog = {
        "catalog": {
            "metadata": {
                "title": f"{concern['name']} Concern Catalog",
                "version": "generated",
                "oscal-version": "1.1.2",
                "props": [
                    prop("catalog-kind", "concern"),
                    prop("catalog-id", f"concerns/{concern['id']}"),
                    prop("characteristic", concern["characteristic"]),
                    prop("lifecycle-status", concern["status"]),
                ],
            },
            "controls": controls,
        }
    }
    return catalog, index_rows


def main():
    if not CONCERNS.exists():
        print("no catalogs/concerns directory found")
        return 0

    (DIST / "concerns").mkdir(parents=True, exist_ok=True)
    all_index = []
    n = 0
    for concern_dir in sorted(p for p in CONCERNS.iterdir() if p.is_dir()):
        if not (concern_dir / "concern.yaml").exists():
            continue
        catalog, rows = assemble_concern(concern_dir)
        out = DIST / "concerns" / f"{concern_dir.name}.oscal.yaml"
        with open(out, "w") as fh:
            fh.write("# GENERATED by tooling/assemble/assemble.py. Do not hand-edit.\n")
            yaml.safe_dump(catalog, fh, sort_keys=False, default_flow_style=False, width=80)
        all_index.extend(rows)
        n += 1
        print(f"  assembled {out.relative_to(ROOT)}  ({len(rows)} rule(s))")

    with open(DIST / "index.yaml", "w") as fh:
        fh.write("# GENERATED. Flat id -> path index for fast lookup.\n")
        yaml.safe_dump({"rules": sorted(all_index, key=lambda r: r["id"])}, fh, sort_keys=False)
    print(f"  assembled {(DIST / 'index.yaml').relative_to(ROOT)}  ({len(all_index)} rule(s) total)")
    print(f"OK: assembled {n} concern catalog(s)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
